import { ANARLOG_ACCOUNT_SERVICES_ENABLED } from "~/auth/account-services";

export const ANARLOG_HOSTED_AUTOMATIONS_ENABLED =
  ANARLOG_ACCOUNT_SERVICES_ENABLED;

export const PERSONAL_AUTOMATION_EXECUTION_POLICY = {
  allowHostedServices: ANARLOG_HOSTED_AUTOMATIONS_ENABLED,
} as const;
